# Generated by Django 3.2 on 2021-05-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # initial = True
    #
    # dependencies = [
    #     ('myApp', '0005_auto_20210519_1036'),
    # ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('client', models.ManyToManyField(related_name='diet_client', to='myApp.Person')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_creator', to='myApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='MainFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('calories', models.FloatField(blank=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('weight', models.FloatField(blank=True)),
                ('quantity', models.FloatField(blank=True)),
                ('meal', models.FloatField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.person')),
                ('diet_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.dietplan')),
                ('main_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.mainfood')),
            ],
        ),
    ]
