# Generated by Django 3.2 on 2021-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainworkout',
            name='goal_muscle',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
