# Generated by Django 3.2 on 2021-05-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_superuser',
        ),
    ]
